import torch
import torch.optim as optim
import torch.utils.data as data
import numpy as np
import matplotlib.pyplot as plt
import os
from tqdm import tqdm # Import tqdm

# Import the model from your model.py file
from model import ConditionalEBM

# --- Configuration ---
DEVICE = torch.device("cpu")
DATA_FILE = os.path.join('data', 'synthetic_dataset.npz')
MODEL_SAVE_PATH = 'trained_ebm.pth'

# Training Hyperparameters
LEARNING_RATE = 1e-4
BATCH_SIZE = 128
EPOCHS = 50

# Langevin Dynamics Hyperparameters
LANGEVIN_STEPS = 60
LANGEVIN_STEP_SIZE = 10
NOISE_SCALE = 0.1

def load_data(filepath):
    """Loads the dataset and prepares it for PyTorch."""
    print(f"Loading data from {filepath}...")
    try:
        dataset = np.load(filepath)
    except FileNotFoundError:
        print(f"Error: Data file not found at {filepath}")
        print("Please run the data_generation.py script first.")
        return None, None
    observations = torch.from_numpy(dataset['observations']).unsqueeze(1)
    labels = torch.from_numpy(dataset['labels']).long()
    dataset = data.TensorDataset(observations, labels)
    dataloader = data.DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)
    print("Data loaded successfully.")
    return dataloader, observations.shape[2:]

def generate_samples_langevin(model, labels, raster_shape):
    """Generates fake data samples using Langevin Dynamics."""
    x_fake = torch.rand(len(labels), 1, *raster_shape, device=DEVICE)
    model.eval()
    for _ in range(LANGEVIN_STEPS):
        x_fake.requires_grad_(True)
        energy = model(x_fake, labels)
        energy.sum().backward()
        with torch.no_grad():
            gradient = x_fake.grad.data
            x_fake = x_fake - LANGEVIN_STEP_SIZE * gradient
            noise = torch.randn_like(x_fake) * NOISE_SCALE
            x_fake += noise
            x_fake.clamp_(0, 1)
    model.train()
    return x_fake.detach()

def train_ebm(dataloader, raster_shape):
    """Main training loop for the EBM with a tqdm progress bar."""
    model = ConditionalEBM(raster_shape=raster_shape, n_classes=4).to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    
    print("\n--- Starting EBM Training ---")
    for epoch in range(EPOCHS):
        total_loss = 0.0
        # --- Wrap the dataloader with tqdm for a progress bar ---
        progress_bar = tqdm(dataloader, desc=f"Epoch {epoch+1}/{EPOCHS}")
        for x_real, s_real in progress_bar:
            x_real = x_real.to(DEVICE)
            s_real = s_real.to(DEVICE)
            
            # Positive Phase
            real_energy = model(x_real, s_real)
            
            # Negative Phase
            x_fake = generate_samples_langevin(model, s_real, raster_shape)
            fake_energy = model(x_fake, s_real)
            
            # Calculate Loss and Update
            loss = real_energy.mean() - fake_energy.mean()
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            # Update the progress bar with the current average loss
            progress_bar.set_postfix(loss=f"{total_loss / (progress_bar.n + 1):.4f}")
            
    print("--- Training Finished ---")
    torch.save(model.state_dict(), MODEL_SAVE_PATH)
    print(f"Model saved to {MODEL_SAVE_PATH}")
    return model

def visualize_generated_samples(model, raster_shape, n_samples=4):
    """Generates and plots samples from the trained model for each class."""
    print("\n--- Generating samples from the trained model ---")
    fig, axes = plt.subplots(n_samples, 4, figsize=(12, 3 * n_samples))
    fig.suptitle("Samples Generated by Trained EBM", fontsize=16)
    class_names = ["Baseline", "Local Cluster", "Global Burst", "Multi-Cluster"]
    for class_idx in range(4):
        labels = torch.full((n_samples,), class_idx, dtype=torch.long, device=DEVICE)
        generated_rasters = generate_samples_langevin(model, labels, raster_shape)
        for sample_idx in range(n_samples):
            ax = axes[sample_idx, class_idx]
            raster = generated_rasters[sample_idx].squeeze().cpu().numpy()
            ax.imshow(raster, cmap='gray_r', interpolation='nearest', aspect='auto')
            if sample_idx == 0:
                ax.set_title(f"Class {class_idx}\n({class_names[class_idx]})")
            ax.set_xticks([]); ax.set_yticks([])
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

# --- Main Execution Block ---
if __name__ == "__main__":
    dataloader, raster_shape = load_data(DATA_FILE)
    if dataloader is not None:
        trained_model = train_ebm(dataloader, raster_shape)
        visualize_generated_samples(trained_model, raster_shape)
